- name: Create AEM group
  group:
    name: "{{ aem_group }}"
    state: present

- name: Create AEM user
  user:
    name: "{{ aem_user }}"
    group: "{{ aem_group }}"
    shell: "/bin/false"
    state: present

- name: Install java
  apt:  
    pkg: openjdk-8-jdk-headless
    state: present

- name: Create AEM Publish root dir "{{ aem_path }}" 
  file:
    path: "{{ aem_path }}"
    state: directory
    mode: '0755'
    owner: "{{ aem_user }}"
    group: "{{ aem_group }}"

- name: AEM download
  get_url:
    url: "{{ aem_dist_url }}/6.5/aem.jar"
    dest: "{{ aem_path }}/aem-author-p4502.jar"
    mode: '0644'
    owner: "{{ aem_user }}"
    group: "{{ aem_group }}"

- name: AEM license download
  get_url:
    url: "{{ aem_dist_url }}/licenses/6.5/license.properties"
    dest: "{{ aem_path }}"
    mode: '0644'
    owner: "{{ aem_user }}"
    group: "{{ aem_group }}"

- name: AEM unpack
  command: java -jar "{{ aem_path }}/aem-publish-p4503.jar" -unpack
  args:
    chdir: "{{ aem_path }}"

- name: Change dir owner
  file:
    path: "{{ aem_path }}"
    state: directory
    recurse: yes
    owner: "{{ aem_user }}"
    group: "{{ aem_group }}"

- name: Change AEM startup script for AEM Publish (port)
  lineinfile:
    path: "{{ aem_path }}/crx-quickstart/bin/start"
    regexp: 'CQ_PORT=4502'
    line: CQ_PORT=4503

- name: Change AEM startup script for AEM Publish (mode)
  lineinfile:
    path: "{{ aem_path }}/crx-quickstart/bin/start"
    regexp: "CQ_RUNMODE='author'"
    line: CQ_RUNMODE='publish'

- name: Create systemd config
  template:
    src: "aem-publish.service.j2"
    dest: "/etc/systemd/system/aem-publish.service"

- name: Enable AEM publish service
  systemd:
    name: aem-publish
    enabled: yes
    masked: no

- name: Make sure a service unit is running
  systemd:
    state: started
    name: aem-publish
    daemon_reload: true

